"""test

Revision ID: 518094bcdaa0
Revises: f01cb2a74923
Create Date: 2018-04-06 15:58:06.214024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '518094bcdaa0'
down_revision = 'f01cb2a74923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy_db', 'test_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy_db', sa.Column('test_column', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
