"""empty message

Revision ID: 67a54b551983
Revises: e4f67a8a4826
Create Date: 2018-04-06 15:55:59.470602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67a54b551983'
down_revision = 'e4f67a8a4826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy_db', 'test_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy_db', sa.Column('test_column', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
