"""empty message

Revision ID: d406ed227059
Revises: 
Create Date: 2018-04-06 14:36:52.168726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd406ed227059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_db',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('proxy_ip', sa.VARCHAR(length=60), nullable=False),
    sa.Column('proxy_port', sa.INTEGER(), nullable=False),
    sa.Column('proxy_country', sa.VARCHAR(length=255), nullable=False),
    sa.Column('proxy_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('addtime', sa.DATETIME(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('last_test_time', sa.DATETIME(), nullable=True),
    sa.Column('proxy_status', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('proxy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('proxy_ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('proxy_port', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('proxy_country', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('proxy_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('addtime', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Last_test_time', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('proxy_status', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('Remarks', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('proxy_db')
    # ### end Alembic commands ###
