"""empty message

Revision ID: e4f67a8a4826
Revises: d406ed227059
Create Date: 2018-04-06 14:37:50.465509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f67a8a4826'
down_revision = 'd406ed227059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy_db', sa.Column('test_column', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy_db', 'test_column')
    # ### end Alembic commands ###
