"""test

Revision ID: f01cb2a74923
Revises: 67a54b551983
Create Date: 2018-04-06 15:57:22.620851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01cb2a74923'
down_revision = '67a54b551983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy_db', sa.Column('test_column', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy_db', 'test_column')
    # ### end Alembic commands ###
